/*
 * TimesheetmanagementSuite.java
 * JUnit based test
 *
 * Created on January 14, 2007, 2:13 AM
 */

package timesheetmanagement;

import junit.framework.*;

/**
 *
 * @author shoukat
 */
public class TimesheetmanagementSuite extends TestCase {
    
    public TimesheetmanagementSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("TimesheetmanagementSuite");
        suite.addTest(timesheetmanagement.SessionBean1Test.suite());
        suite.addTest(timesheetmanagement.Page1Test.suite());
        suite.addTest(timesheetmanagement.ApplicationBean1Test.suite());
        suite.addTest(timesheetmanagement.RequestBean1Test.suite());
        return suite;
    }
    
}
