/*
 * DAOSuite.java
 * JUnit based test
 *
 * Created on January 14, 2007, 2:13 AM
 */

package DAO;

import junit.framework.*;

/**
 *
 * @author shoukat
 */
public class DAOSuite extends TestCase {
    
    public DAOSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("DAOSuite");
        suite.addTest(DAO.EmployeedaoTest.suite());
        suite.addTest(DAO.Timesheet_hourdaoTest.suite());
        suite.addTest(DAO.timesheetdaoTest.suite());
        suite.addTest(DAO.Employee_clientdaoTest.suite());
        return suite;
    }
    
}
