import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on January 14, 2007, 2:13 AM
 */

/**
 *
 * @author shoukat
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(timesheetmanagement.TimesheetmanagementSuite.suite());
        suite.addTest(DAO.DAOSuite.suite());
        suite.addTest(Buissness.BuissnessSuite.suite());
        return suite;
    }
    
}
